version: '3.0'

services:
  web:
    build: .
    entrypoint: >
      bash -c "
      rm -f tmp/pids/server.pid
      && bundle exec rails s -b 0.0.0.0 -p 9000"
    ports:
      - 9000:9000
    volumes:
      - .:/src/myapp
    depends_on:
      - db
    links:
      - "db:db"
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'clickupmedia'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_data:
